procedure InitializeComponent;
    begin
        self.SuspendLayout();
        // 
        // ContextBaForm
        // 
        self.ClientSize := new System.Drawing.Size(1048, 40);
        self.FormBorderStyle := System.Windows.Forms.FormBorderStyle.FixedToolWindow;
        self.MaximizeBox := false;
        self.Name := 'ContextBaForm';
        self.Text := 'Form1';
        self.ResumeLayout(false);
    end;
